version: '3.7'
services:
  nginx:
    image: nginx:1.17
    user: ${whoami}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: bash worker.sh
    user: ${whoami}
    environment:
      ENABLE_SENTRY: 'yes'
      ENVIRONMENT: DEV
      DATABASE_URL: 'postgresql://aurora:AuroraAdminPanel321@postgres:5432/aurora'
      DDNS_INTERVAL_SECONDS: 60000
      TRAFFIC_INTERVAL_SECONDS: 10000
    volumes:
      - /home/lei/.ssh/id_rsa:/app/ansible/env/ssh_key
      - ./backend:/app

  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: aurora
      POSTGRES_PASSWORD: AuroraAdminPanel321
    volumes:
      - db-data:/var/lib/postgresql/data
      
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
      args:
        BACKEND_APP_VERSION: local
    command: bash -c "while !</dev/tcp/postgres/5432; do sleep 1; done; alembic upgrade heads && python app/main.py"
    user: ${whoami}
    tty: true
    environment:
      PYTHONPATH: .
      ENABLE_SENTRY: 'yes'
      ENVIRONMENT: DEV
      DATABASE_URL: 'postgresql://aurora:AuroraAdminPanel321@postgres:5432/aurora'
      SECREY_KEY: 'd7Wn3VRWMWPqpM5rqsdRAvW$$2Y7&MTwqnEFZrxA!tNDd&p9F#quNp*SsKzd&AWSLap!NkvW7DPsHktcJPA&cw@bZ$$hxpprDdGKk*h53tL47dDH2epM6JaqD6mfju4&bz'
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile-dev
    stdin_open: true
    user: ${whoami}
    command: bash -c "yarn && yarn start"
    ports:  
        - 3000:3000
    environment:
      - NODE_ENV=development
      - REACT_APP_VERSION=local
    volumes:
      - ./frontend:/app

  redis:
    image: redis
    restart: always

  adminer:
    image: adminer
    restart: always
    ports:
      - 8070:8080
  
volumes:
  db-data:
