version: '3.7'
services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/var/www/html
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend

  redis:
    image: redis
    ports:
      - 6379:6379

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery -A app.tasks worker --loglevel=INFO -Q main-queue -c 5
    environment:
      DATABASE_URL: 'sqlite:///app.db'
    volumes:
      - ./backend:/app

  flower:  
    image: mher/flower:0.9.5
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:  
        - 5555:5555
    depends_on:
      - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'sqlite:///app.db'

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    command: bash -c "npm install && npm start"
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    ports:  
        - 3000:3000
    environment:
      - NODE_ENV=development
  